// src/views/settings/About.vue
<template>
  <div style="text-align: center; margin-top: 20px">
    <div style="justify-self: center" class="logo">
      <img style="width: 80px" src="/logo.svg"/>
    </div>
    <h3 class="description">Flexmodel | All-in-one API design platform</h3>
    <div style="margin-top: 10px">
      <div w="full" py="4" style="text-align: center;">
        <p>
          See
          <a href="https://github.com/flexmodel-project" target="_blank">flexmodel project</a> for more
          information.
        </p>
      </div>
    </div>
  </div>

</template>
<script setup lang="ts">

</script>
<style scoped>

</style>

// src/pages/Settings/components/About.tsx
import React from 'react';
import { Typography } from 'antd';

const { Title, Paragraph } = Typography;

const About: React.FC = () => {
  return (
    <div style={{ textAlign: 'center', marginTop: '20px' }}>
      <div className="logo" style={{ justifySelf: 'center' }}>
        <img style={{ width: '80px' }} src="/logo.svg" alt="Flexmodel Logo" />
      </div>
      <Title level={3} className="description">
        Flexmodel | All-in-one API design platform
      </Title>
      <div style={{ marginTop: '10px' }}>
        <div style={{ width: '100%', padding: '16px', textAlign: 'center' }}>
          <Paragraph>
            See{' '}
            <a href="https://github.com/flexmodel-project" target="_blank" rel="noopener noreferrer">
              flexmodel project
            </a>{' '}
            for more information.
          </Paragraph>
        </div>
      </div>
    </div>
  );
};

export default About;
