// src/pages/DataModeling/components/RecordList.tsx
import React, {useState, useEffect} from 'react';
import {Button, Card, Col, Form, Input, Modal, Row, Switch, Table, Pagination, message, DatePicker} from 'antd';
import {ColumnsType} from 'antd/es/table';
import {DeleteOutlined, EditOutlined} from "@ant-design/icons";

interface Field {
  name: string;
  type: string;
  nullable?: boolean;
  comment?: string;
}

interface Record {
  [key: string]: any;
}

interface Model {
  name: string;
  comment?: string;
  fields: Field[];
  idField?: Field;
}

interface RecordListProps {
  datasource: string;
  model: Model;
  createRecord?: (datasource: string, modelName: string, data: Record) => Promise<void>;
  updateRecord?: (datasource: string, modelName: string, id: any, data: Record) => Promise<void>;
  deleteRecord?: (datasource: string, modelName: string, id: any) => Promise<void>;
  getRecordList?: (datasource: string, modelName: string, query: { current: number; pageSize: number }) => Promise<{ list: Record[]; total: number }>;
}

const RecordList: React.FC<RecordListProps> = ({ datasource, model, createRecord, updateRecord, deleteRecord, getRecordList }) => {
  const [dialogFormVisible, setDialogFormVisible] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const [editMode, setEditMode] = useState<boolean>(false);
  const [records, setRecords] = useState<{ list: Record[]; total: number }>({list: [], total: 0});
  const [form] = Form.useForm();
  const [query, setQuery] = useState({current: 1, pageSize: 10, filter: '', sort: ''});

  useEffect(() => {
    fetchRecords();
  }, [query, model]);

  useEffect(() => {
    // Define form rules based on the model fields
    const rules: any = {};
    model.fields.forEach(field => {
      rules[field.name] = [{required: !field.nullable, message: `Please input ${field.name}`}];
    });
    form.setFields(Object.keys(rules).map(key => ({
      name: key,
      rules: rules[key]
    })));
  }, [form, model.fields]);

  const fetchRecords = async () => {
    setLoading(true);
    const data = await getRecordList(datasource, model.name, query);
    setRecords(data);
    setLoading(false);
  };

  const handleEdit = (record: Record) => {
    setDialogFormVisible(true);
    setEditMode(true);
    form.setFieldsValue(record);
  };

  const handleDelete = async (record: Record) => {
    if (!model.idField) {
      message.warning("Can't delete a record without ID!");
      return;
    }
    await deleteRecord(datasource, model.name, record[model.idField.name]);
    fetchRecords();
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      if (editMode) {
        await updateRecord(datasource, model.name, values[model.idField?.name], values);
      } else {
        await createRecord(datasource, model.name, values);
      }
      fetchRecords();
      setDialogFormVisible(false);
    } catch (errorInfo) {
      console.log('Failed:', errorInfo);
    }
  };

  const columns: ColumnsType<Record> = [
    ...model.fields.map(field => ({
      title: field.name,
      dataIndex: field.name,
      key: field.name,
      width: 100,

      render: (text: any) => (typeof text === 'object' ? JSON.stringify(text) : text),
    })),
    {
      title: 'Operations',
      key: 'operations',
      fixed: 'right',
      width: 120,
      render: (_, record) => (
        <>
          <Button size="small" type="link" icon={<EditOutlined/>} onClick={() => handleEdit(record)}>Edit</Button>
          <Button size="small" type="link" icon={<DeleteOutlined/>} danger onClick={() => handleDelete(record)}
                  style={{marginLeft: 8}}>
            Delete
          </Button>
        </>
      ),
    },
  ];

  return (
    <div style={{padding: '20px'}}>
      <Row>
        <Col span={24}>
          <div>
            <Row>
              <Col span={12}>
                {model.name} {model.comment}
              </Col>
              <Col span={12} style={{textAlign: 'right'}}>
                <Button type="primary" onClick={() => {
                  setDialogFormVisible(true);
                  setEditMode(false);
                }}>
                  New Record
                </Button>
              </Col>
            </Row>
          </div>
        </Col>
      </Row>
      <Row>
        <Col span={24}>
          <div  style={{marginTop: 16}}>
            <Table
              loading={loading}
              scroll={{x: 1500, y: 400}}
              style={{width: '100%'}}
              size="small"
              columns={columns}
              dataSource={records.list}
              pagination={false}
              rowKey={(record) => record[model.idField?.name] || 'id'}
            />
            <div style={{marginTop: 16}}>
              <Pagination
                align="end"
                showTotal={(total, range) => `${range[0]}-${range[1]} of ${total} items`}
                current={query.current}
                pageSize={query.pageSize}
                total={records.total}
                onChange={(page, pageSize) => setQuery(prev => ({...prev, current: page, pageSize}))}
                pageSizeOptions={[10, 20, 50, 100]}
              />
            </div>
          </div>
        </Col>
      </Row>
      <Modal
        title={editMode ? `Edit ${model.name} Record` : `New ${model.name} Record`}
        visible={dialogFormVisible}
        onCancel={() => setDialogFormVisible(false)}
        onOk={handleSubmit}
        width={600}
      >
        <Form
          form={form}
          layout="vertical"
        >
          {model.fields.map(field => (
            <Form.Item
              key={field.name}
              name={field.name}
              label={field.name}
              rules={[{required: !field.nullable, message: `Please input ${field.name}`}]}
            >
              {field.type === 'id' ? (
                <Input disabled={editMode}/>
              ) : field.type === 'string' ? (
                <Input placeholder={field.comment}/>
              ) : field.type === 'text' ? (
                <Input.TextArea placeholder={field.comment}/>
              ) : field.type === 'decimal' || field.type === 'int' || field.type === 'bigint' ? (
                <Input type="number" placeholder={field.comment}/>
              ) : field.type === 'boolean' ? (
                <Switch/>
              ) : field.type === 'date' ? (
                <DatePicker placeholder={field.comment} style={{width: '100%'}}/>
              ) : field.type === 'datetime' ? (
                <DatePicker picker="datetime" placeholder={field.comment} style={{width: '100%'}}/>
              ) : field.type === 'json' ? (
                <Input.TextArea placeholder={field.comment}/>
              ) : (
                <Input/>
              )}
            </Form.Item>
          ))}
        </Form>
      </Modal>
    </div>
  );
};

export default RecordList;

// src/views/modeling/RecordList.vue
<template>
  <el-row>
    <el-col>
      <el-card shadow="never">
        <el-row>
          <el-col :span="12">{{ model?.name }}
            {{ model?.comment }}
          </el-col>
          <el-col :span="12" style="text-align: right">
            <el-button type="primary" @click="dialogFormVisible = true">New record</el-button>
          </el-col>
        </el-row>
      </el-card>
    </el-col>
    <el-col>
      <el-card shadow="never">
        <el-table :data="records.list" height="428" style="width: 100%">
          <el-table-column v-for="item in model?.fields"
                           :label="item.name"
                           :prop="item.name"
                           :show-overflow-tooltip="item.type==='text'||item.type==='json'">
            <template #default="{ row }">
              {{ row[item.name] }}
            </template>
          </el-table-column>
          <el-table-column label="operations" width="150" fixed="right">
            <template #default="scope">
              <el-button type="primary" link @click="handleEdit(scope.row)">
                Edit
              </el-button>
              <el-popconfirm title="Are you sure to delete this?" @confirm="reqDeleteRecord(scope.row)">
                <template #reference>
                  <el-button type="primary" link>
                    Delete
                  </el-button>
                </template>
              </el-popconfirm>
            </template>
          </el-table-column>
        </el-table>
        <div class="pagination">
          <el-pagination
            class="flex justify-end mr-10px mt-12px"
            v-model:current-page="query.current"
            v-model:page-size="query.pageSize"
            :page-sizes="[10, 20, 50, 100]"
            layout="total, sizes, prev, pager, next, jumper"
            :total="records.total"
          />
        </div>
      </el-card>
    </el-col>
  </el-row>
  <el-dialog @close="resetForm(formRef)" v-model="dialogFormVisible"
             :title="editMode?`Edit ${model.name} record`:`New ${model.name} record`" width="600">
    <el-form ref="formRef" :model="form" :rules="rules" label-width="auto" status-icon>
      <el-form-item v-for="field in model.fields"
                    :label="field.name"
                    :prop="field.name"
                    :required="!field.nullable">
        <el-input v-if="field.type=='id'" :disabled="editMode" v-model="form[field.name]"/>
        <el-input v-else-if="field.type=='string'" :placeholder="field.comment" v-model="form[field.name]"/>
        <el-input v-else-if="field.type=='text'" :placeholder="field.comment" type="textarea"
                  v-model="form[field.name]"/>
        <el-input v-else-if="field.type=='decimal'" :placeholder="field.comment" type="number"
                  v-model="form[field.name]"/>
        <el-input v-else-if="field.type=='int'" :placeholder="field.comment" type="number" v-model="form[field.name]"/>
        <el-input v-else-if="field.type=='bigint'" :placeholder="field.comment" v-model="form[field.name]"/>
        <el-switch v-else-if="field.type=='boolean'" :placeholder="field.comment" v-model="form[field.name]"/>
        <el-date-picker v-else-if="field.type=='date'" :placeholder="field.comment" type="date"
                        v-model="form[field.name]" style="width: 100%;"/>
        <el-date-picker v-else-if="field.type=='datetime'" type="datetime"
                        :placeholder="field.comment" v-model="form[field.name]" style="width: 100%;"/>
        <el-input v-else-if="field.type=='json'" :placeholder="field.comment" type="textarea"
                  v-model="form[field.name]"/>
        <el-input v-else v-model="form[field.name]"/>
      </el-form-item>
    </el-form>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="resetForm(formRef)">Cancel</el-button>
        <el-button type="primary" @click="submitForm(formRef)">
          {{ editMode ? 'Save changes' : 'Create' }}
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>
<script setup lang="ts">
import {computed, ref, watchEffect} from "vue";
import {createRecord, deleteRecord, getRecordList, updateRecord} from "~/api/record";
import type {FormInstance, FormRules} from 'element-plus'

const props = defineProps(['datasource', 'model']);

const dialogFormVisible = ref(false);
const editMode = ref<boolean>(false);
const query = ref({
  current: 1,
  pageSize: 10,
  filter: '',
  sort: '',
});
const records = ref<any[]>([]);
const form = ref<any>({});
const rules = ref<FormRules<any>>({});
const formRef = ref<FormInstance>();

const datasource = computed(() => props.datasource);
const model = computed(() => props.model);

const reqRecordList = async () => {
  records.value = await getRecordList(props.datasource, props.model?.name, {
    current: query.value.current,
    pageSize: query.value.pageSize
  });
};
const reqDeleteRecord = async (record: any) => {
  if (!model.value?.idField) {
    ElMessage.warning("Can't delete a record without ID!");
  }
  await deleteRecord(props.datasource, model.value.name, record[model.value?.idField?.name]);
  await reqRecordList();
};
const submitForm = async (formEl: FormInstance | undefined) => {
  if (!formEl) return;
  await formEl.validate(async (valid) => {
    if (valid) {
      if (editMode.value) {
        await updateRecord(props.datasource, model.value.name, form.value[model.value?.idField?.name], form.value);
      } else {
        await createRecord(props.datasource, model.value.name, form.value);
      }
      await reqRecordList();
      dialogFormVisible.value = false;
    }
  });
};
const resetForm = (formEl: FormInstance | undefined) => {
  dialogFormVisible.value = false;
  if (!formEl) return;
  formEl.resetFields();
  Object.keys(form.value).forEach(key => form.value[key] = '');
  editMode.value = false;
}
const handleEdit = (record: any) => {
  dialogFormVisible.value = true;
  editMode.value = true;
  Object.keys(record).forEach((key: string) => {
    const value = record[key];
    form.value[key] = value !== null && typeof value === 'object' ? JSON.stringify(value) : value;
  });
};

watchEffect(() => {
  if (props.model) {
    reqRecordList();
    props.model.fields.forEach((field: any) => {
      rules.value[field.name] = [
        {
          required: !field.nullable,
          message: `Please input ${field.name}`
        }
      ];
    });
  }
});
</script>
<style scoped>
</style>
