// src/views/idps/IdPInfo.vue
<template>
  <el-descriptions border :column="1">
    <el-descriptions-item label="Display name">{{ data.name }}</el-descriptions-item>
    <el-descriptions-item label="Provider type">{{ data.provider?.type }}</el-descriptions-item>
    <el-descriptions-item label="Issuer">{{ data.provider?.issuer }}</el-descriptions-item>
    <el-descriptions-item v-if="data.provider?.issuer" label="Discovery endpoint">{{ data.provider?.issuer }}/.well-known/openid-configuration
    </el-descriptions-item>
    <el-descriptions-item label="Client ID">{{ data.provider?.clientId }}</el-descriptions-item>
    <el-descriptions-item label="Client Secret">
      <HidePassword :text="data.provider?.clientSecret"/>
    </el-descriptions-item>
  </el-descriptions>
</template>
<script setup lang="ts">
import HidePassword from "~/components/HidePassword.vue";

const data = defineModel<any>({required: true});

</script>
<style scoped>

</style>

// src/pages/IdPManagement/components/IdPInfo.tsx
import React from 'react';
import {Descriptions} from 'antd';
import HidePassword from "../../../components/HidePassword.tsx";

interface IdpInfoProps {
  data: {
    name: string;
    provider?: {
      type: string;
      issuer: string;
      clientId: string;
      clientSecret: string;
    };
  };
}

const IdpInfo: React.FC<IdpInfoProps> = ({data}) => {
  return (
    <Descriptions bordered column={1}>
      {/* Display name */}
      <Descriptions.Item label="Display name">{data.name}</Descriptions.Item>

      {/* Provider type */}
      <Descriptions.Item label="Provider type">{data.provider?.type}</Descriptions.Item>

      {/* Issuer */}
      <Descriptions.Item label="Issuer">{data.provider?.issuer}</Descriptions.Item>

      {/* Discovery endpoint */}
      {data.provider?.issuer && (
        <Descriptions.Item label="Discovery endpoint">
          {`${data.provider.issuer}/.well-known/openid-configuration`}
        </Descriptions.Item>
      )}

      {/* Client ID */}
      <Descriptions.Item label="Client ID">{data.provider?.clientId}</Descriptions.Item>

      {/* Client Secret */}
      <Descriptions.Item label="Client Secret">
        <HidePassword text={data.provider?.clientSecret}/>
      </Descriptions.Item>
    </Descriptions>
  );
};

export default IdpInfo;
