// src/pages/Settings/components/Variables.tsx
import React, { useEffect, useState } from 'react';
import { Card, Col, Input, Row, Table, Collapse } from 'antd';
import { getVariables } from "../../../api/environment.ts";
import HidePassword from "../../../components/HidePassword.tsx";

const { Panel } = Collapse;

const Variables: React.FC = () => {
  const [variables, setVariables] = useState<{ environment: Record<string, string>, system: Record<string, string> }>({ environment: {}, system: {} });
  const [filterKeyword, setFilterKeyword] = useState<string>('');

  // 获取变量数据
  useEffect(() => {
    const fetchVariables = async () => {
      const vars = await getVariables();
      setVariables(vars);
    };
    fetchVariables();
  }, []);

  // 过滤环境变量
  const environmentVariables = Object.keys(variables.environment || {})
    .filter(key => key.includes(filterKeyword))
    .map(key => ({ key, value: variables.environment[key] }));

  // 过滤系统变量
  const systemVariables = Object.keys(variables.system || {})
    .filter(key => key.includes(filterKeyword))
    .map(key => ({ key, value: variables.system[key] }));

  // 表格列定义
  const columns = [
    {
      title: 'Variable Name',
      dataIndex: 'key',
      key: 'key',
      width: 500,
    },
    {
      title: 'Variable Value',
      dataIndex: 'value',
      key: 'value',
      render: (text: string) => <HidePassword text={text} />,
    },
  ];

  return (
    <Card>
      <Row>
        <Col span={12}>
          <h2>Variables</h2>
        </Col>
        <Col span={6}></Col>
        <Col span={6}>
          <Input
            placeholder="Search variables"
            value={filterKeyword}
            onChange={(e) => setFilterKeyword(e.target.value)}
            allowClear
          />
        </Col>
      </Row>

      <div style={{ height: '540px', overflow: 'auto' }}>
        <Collapse defaultActiveKey={['1','2']} ghost>
          <Panel header="Environment Variables" key="1">
            <Table
              size="small"
              dataSource={environmentVariables}
              columns={columns}
              pagination={false}
              rowKey="key"
            />
          </Panel>
          <Panel header="System Variables" key="2">
            <Table
              size="small"
              dataSource={systemVariables}
              columns={columns}
              pagination={false}
              rowKey="key"
            />
          </Panel>
        </Collapse>
      </div>
    </Card>
  );
};

export default Variables;

// src/views/settings/Variables.vue
<template>
  <el-card>
    <template #header>
      <el-row>
        <el-col :span="12">Variables</el-col>
        <el-col :span="6">
        </el-col>
        <el-col :span="6">
          <el-input placeholder="Search variables" v-model="filterKeyword" clearable/>
        </el-col>
      </el-row>
    </template>

    <el-scrollbar height="560px">
      <el-row>
        <el-col>
          <div class="font-bold pt7 pb7">Environment variables</div>
          <el-table :data="environmentVariables" stripe style="width: 100%">
            <el-table-column prop="key" label="Variable Name" width="300px"/>
            <el-table-column prop="value" label="Variable value">
              <template #default="{row}">
                <HidePassword :text="row.value"/>
              </template>
            </el-table-column>
          </el-table>
        </el-col>
        <el-col>
          <div class="font-bold pt7 pb7">System variables</div>
          <el-table :data="systemVariables" stripe style="width: 100%">
            <el-table-column prop="key" label="Variable Name" width="300px"/>
            <el-table-column prop="value" label="Variable value">
              <template #default="{row}">
                <HidePassword :text="row.value"/>
              </template>
            </el-table-column>
          </el-table>
        </el-col>
      </el-row>
    </el-scrollbar>
  </el-card>
</template>
<script setup lang="ts">

import HidePassword from "~/components/HidePassword.vue";
import {computed, ref} from "vue";
import {getVariables} from "~/api/environment";

const variables = ref<any>({});
const reqVariables = async () => {
  variables.value = await getVariables()
}
const filterKeyword = ref<string>('');
reqVariables();
const environmentVariables = computed(() => {
  const list = [];
  const keys = Object.keys(variables.value['environment'] || {});
  keys.filter(k => k.includes(filterKeyword.value)).forEach(key => list.push({
    key: key,
    value: variables.value['environment'][key]
  }));
  return list;
});
const systemVariables = computed(() => {
  const list = [];
  const keys = Object.keys(variables.value['system'] || {});
  keys?.filter(k => k.includes(filterKeyword.value)).forEach(key => list.push({
    key: key,
    value: variables.value['system'][key]
  }));
  return list;
});
</script>

<style scoped>

</style>
