// src/components/HoverEditInput.vue
<template>
  <el-input ref="inputRef" v-model="val" @keyup.enter="handleKeyEnter" size="small"/>
</template>
<script setup lang="ts">
import {ref, watchEffect} from "vue";
import {InputInstance} from "element-plus";

const emits = defineEmits(['change']);

const val = defineModel<string>({required: true});

const inputRef = ref<InputInstance>()

const handleKeyEnter = () => {
  emits('change', inputRef.value);
}

watchEffect(() => {
  if (val.value) {
    inputRef.value?.focus();
    inputRef.value?.select();
  }
})
</script>

// src/pages/ApiManagement/components/HoverEditInput.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Input } from 'antd';

interface HoverEditInputProps {
  value: string;
  onChange: (value: string) => void;
}

const HoverEditInput: React.FC<HoverEditInputProps> = ({ value, onChange }) => {
  const [val, setVal] = useState<string>(value);
  const inputRef = useRef<any>(null);

  const handleKeyEnter = () => {
    onChange(val);
  };

  useEffect(() => {
    if (val) {
      inputRef.current?.focus();
      inputRef.current?.select();
    }
  }, [val]);

  return (
    <Input
      ref={inputRef}
      value={val}
      onChange={(e) => setVal(e.target.value)}
      onPressEnter={handleKeyEnter}
      size="small"
    />
  );
};

export default HoverEditInput;
