// src/pages/Datasource/components/DatabaseInfo.tsx
import React from 'react';
import { Descriptions, Typography } from 'antd';
import HidePassword from "../../../components/HidePassword.tsx";

interface Datasource {
  name: string;
  type: string;
  config?: {
    dbKind?: string;
    url?: string;
    username?: string;
    password?: string;
  };
  createdAt: string;
}

interface DatabaseInfoProps {
  datasource: Datasource;
}

const DatabaseInfo: React.FC<DatabaseInfoProps> = ({ datasource }) => {
  return (
    <Descriptions bordered column={1}>
      <Descriptions.Item label="Connection name">{datasource.name}</Descriptions.Item>
      <Descriptions.Item label="Connection type">{datasource.type}</Descriptions.Item>
      <Descriptions.Item label="Database type">{datasource.config?.dbKind}</Descriptions.Item>
      <Descriptions.Item label="URL">{datasource.config?.url}</Descriptions.Item>
      {datasource.config?.username && (
        <Descriptions.Item label="Username">{datasource.config.username}</Descriptions.Item>
      )}
      {datasource.config?.password && (
        <Descriptions.Item label="Password">
          <HidePassword text={datasource.config.password} />
        </Descriptions.Item>
      )}
      <Descriptions.Item label="Create time">{datasource.createdAt}</Descriptions.Item>
    </Descriptions>
  );
};

export default DatabaseInfo;

// src/views/datasource/DatabaseInfo.vue
<template>
  <el-descriptions border column="1">
    <el-descriptions-item label="Connection name">{{ datasource.name }}</el-descriptions-item>
    <el-descriptions-item label="Connection type">{{ datasource.type }}</el-descriptions-item>
    <el-descriptions-item label="Database type">{{ datasource.config?.dbKind }}</el-descriptions-item>
    <el-descriptions-item label="URL">{{ datasource.config?.url }}</el-descriptions-item>
    <el-descriptions-item label="Username">{{ datasource.config?.username }}</el-descriptions-item>
    <el-descriptions-item label="Password">
      <HidePassword :text="datasource.config?.password"/>
    </el-descriptions-item>
    <el-descriptions-item label="Create time">{{ datasource.createdAt }}</el-descriptions-item>
  </el-descriptions>
</template>
<script setup lang="ts">
import HidePassword from "~/components/HidePassword.vue";

const props = defineProps(['datasource']);

</script>
<style scoped>

</style>
