// src/pages/DataSource/components/DatabaseInfo.tsx
import React from 'react';
import { Descriptions } from 'antd';
import HidePassword from "../../../components/HidePassword.tsx";

interface Datasource {
  name: string;
  type: string;
  config?: {
    dbKind?: string;
    url?: string;
    username?: string;
    password?: string;
  };
  createdAt: string;
}

interface DatabaseInfoProps {
  datasource: Datasource;
}

const DatabaseInfo: React.FC<DatabaseInfoProps> = ({ datasource }) => {
  return (
    <Descriptions bordered column={1} items={[
      {
        key: 'Connection name',
        label: 'Connection name',
        children: datasource.name,
        span: 1,
      },
      {
        key: 'Connection type',
        label: 'Connection type',
        children: datasource.type,
        span: 1,
      },
      {
        key: 'Database type',
        label: 'Database type',
        children: datasource.config?.dbKind,
        span: 1,
      },
      {
        key: 'URL',
        label: 'URL',
        children: datasource.config?.url,
        span: 1,
      },
      ...(datasource.config?.username ? [{
        key: 'Username',
        label: 'Username',
        children: datasource.config.username,
        span: 1,
      }] : []),
      ...(datasource.config?.password ? [{
        key: 'Password',
        label: 'Password',
        children: <HidePassword text={datasource.config.password} />,
        span: 1,
      }] : []),
      ...(datasource.createdAt ? [{
        key: 'Create time',
        label: 'Create time',
        children: datasource.createdAt,
        span: 1,
      }] : []),
    ]} />
  );
};

export default DatabaseInfo;

// src/views/datasource/DatabaseInfo.vue
<template>
  <el-descriptions border column="1">
    <el-descriptions-item label="Connection name">{{ datasource.name }}</el-descriptions-item>
    <el-descriptions-item label="Connection type">{{ datasource.type }}</el-descriptions-item>
    <el-descriptions-item label="Database type">{{ datasource.config?.dbKind }}</el-descriptions-item>
    <el-descriptions-item label="URL">{{ datasource.config?.url }}</el-descriptions-item>
    <el-descriptions-item label="Username">{{ datasource.config?.username }}</el-descriptions-item>
    <el-descriptions-item label="Password">
      <HidePassword :text="datasource.config?.password"/>
    </el-descriptions-item>
    <el-descriptions-item label="Create time">{{ datasource.createdAt }}</el-descriptions-item>
  </el-descriptions>
</template>
<script setup lang="ts">
import HidePassword from "~/components/HidePassword.vue";

const props = defineProps(['datasource']);

</script>
<style scoped>

</style>
