// src/pages/DataSource/index.tsx
import React, { useEffect, useState } from "react";
import {
  Button,
  Card,
  Divider,
  Dropdown,
  Form,
  Input,
  Menu,
  message,
  Modal,
  Space,
  Spin,
  Tree,
} from "antd";
import Icon, {
  BlockOutlined,
  DeleteOutlined,
  MoreOutlined,
} from "@ant-design/icons";
import DatabaseInfo from "./components/DatabaseInfo.tsx";
import EditDSConfig from "./components/EditDatabaseModal.tsx";
import ConnectDatabaseDrawer from "./components/ConnectDatabaseDrawer.tsx";
import {
  deleteDatasource,
  getDatasourceList,
  importModels as reqImportModels,
  updateDatasource,
  validateDatasource,
} from "../../api/datasource.ts";
import { useNavigate } from "react-router-dom";
import { DbsMap } from "./common.ts";
import { getModelList } from "../../api/model.ts";
import { useTranslation } from "react-i18next";
import styles from "./index.module.scss";

const DatasourceManagement: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [dsList, setDsList] = useState<any[]>([]);
  const [activeDs, setActiveDs] = useState<any>({
    config: { dbKind: "" },
    createTime: "",
    name: "",
    type: "",
  });
  const [dsLoading, setDsLoading] = useState<boolean>(false);
  const [testLoading, setTestLoading] = useState<boolean>(false);
  const [drawerVisible, setDrawerVisible] = useState<boolean>(false);
  const [editVisible, setEditVisible] = useState<boolean>(false);
  const [deleteVisible, setDeleteVisible] = useState<boolean>(false);
  const [importVisible, setImportVisible] = useState<boolean>(false);
  const [exportVisible, setExportVisible] = useState<boolean>(false);

  const [scriptForm] = Form.useForm();

  const fetchDatasourceList = async () => {
    try {
      setDsLoading(true);
      const list = await getDatasourceList();
      setDsList(list);
      if (!activeDs.name) {
        setActiveDs(list[0]);
      }
    } catch (error) {
      message.error("Failed to load datasource list.");
      console.error(error);
    } finally {
      setDsLoading(false);
    }
  };

  useEffect(() => {
    fetchDatasourceList();
  }, []);

  const handleTestConnection = async () => {
    setTestLoading(true);
    try {
      const result = await validateDatasource(activeDs);
      if (result.success) {
        message.success(
          t("test_connection_success_message", { time: result.time })
        );
      } else {
        message.error(
          t("test_connection_fail_message", { msg: result.errorMsg })
        );
      }
    } catch (error) {
      console.log(error);
      message.error(t("test_connection_fail_message_2"));
    } finally {
      setTestLoading(false);
    }
  };

  const handleEdit = async (formData: any) => {
    try {
      const res = await updateDatasource(formData.name, {
        name: formData.name,
        enabled: activeDs.enabled,
        config: {
          dbKind: formData.dbKind,
          username: formData.username,
          password: formData.password,
          url: formData.url,
        },
      });
      setEditVisible(false);
      setActiveDs(res);
      fetchDatasourceList();
    } catch (error) {
      console.error(error);
      message.error("Failed to update datasource.");
    }
  };

  const handleDelete = async () => {
    await deleteDatasource(activeDs.name);
    const list = await getDatasourceList();
    setDsList(list);
    setDeleteVisible(false);
  };

  const handleTreeClick = (item: any) => {
    console.log(item);
    setActiveDs(item);
  };

  const handleExport = async () => {
    const models = await getModelList(activeDs.name);
    const script = {
      schema: models,
      data: [],
    };
    scriptForm.setFieldValue("script", JSON.stringify(script));
    setExportVisible(true);
  };

  const handleImport = () => {
    scriptForm.resetFields();
    setImportVisible(true);
  };
  const importModels = async () => {
    const values = await scriptForm.validateFields();
    reqImportModels(activeDs.name, values).then(() =>
      message.success("Models import successfully")
    );
    setImportVisible(false);
  };

  return (
    <>
      <Card style={{ height: "100%" }} className={styles.root}>
        <div style={{ display: "flex", backgroundColor: "#fff", flex: 1 }}>
          <div
            style={{
              width: "25%",
              borderRight: "1px solid rgba(5, 5, 5, 0.06)",
              padding: "10px 10px 0px 0px",
            }}
          >
            <div
              style={{
                whiteSpace: "nowrap",
                overflow: "hidden",
                textOverflow: "ellipsis",
              }}
            >
              <span style={{ fontWeight: 600, fontSize: "16px" }}>
                {t("datasource_management")}
              </span>
            </div>
            <Divider />
            <Spin spinning={dsLoading}>
              <Tree
                treeData={dsList.map((ds) => ({
                  ...ds,
                  title: ds.name,
                  key: ds.name,
                }))}
                selectedKeys={[activeDs.name]}
                titleRender={(node) => (
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      width: "250px",
                    }}
                  >
                    {<Icon component={DbsMap[node.config?.dbKind]} />}&nbsp;
                    <span>{node.title}</span>
                    <Dropdown
                      overlay={
                        <Menu>
                          <Menu.Item
                            style={{ color: "red" }}
                            icon={<DeleteOutlined />}
                            disabled={node.type === "system"}
                            onClick={() => {
                              setDeleteVisible(true);
                            }}
                          >
                            {t("delete")}
                          </Menu.Item>
                        </Menu>
                      }
                      trigger={["hover"]}
                      placement="bottomRight"
                    >
                      <MoreOutlined
                        style={{ marginLeft: "auto", cursor: "pointer" }}
                      />
                    </Dropdown>
                  </div>
                )}
                onSelect={(_, { node }) => handleTreeClick(node)}
              />
            </Spin>
            <Divider />
            <Button
              type="primary"
              icon={<BlockOutlined />}
              onClick={() => setDrawerVisible(true)}
              style={{ width: "100%" }}
              ghost
            >
              {t("connect_datasource")}
            </Button>
          </div>
          <div style={{ width: "75%", padding: "8px 20px" }}>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                paddingBottom: "10px",
              }}
            >
              <div>{activeDs.name}</div>
              <div>
                <Space>
                  <Button onClick={handleImport}>{t("import")}</Button>
                  <Button onClick={handleExport}>{t("export")}</Button>
                  <Button
                    onClick={() => {
                      navigate(`/modeling?datasource=${activeDs.name}`);
                    }}
                  >
                    {t("modeling")}
                  </Button>
                  <Button onClick={handleTestConnection} loading={testLoading}>
                    {t("test")}
                  </Button>
                  <Button
                    type="primary"
                    disabled={activeDs.type === "system"}
                    onClick={() => setEditVisible(true)}
                  >
                    {t("edit")}
                  </Button>
                </Space>
              </div>
            </div>
            <div>
              <DatabaseInfo datasource={activeDs} />
            </div>
          </div>
        </div>
        <ConnectDatabaseDrawer
          visible={drawerVisible}
          onChange={(data) => {
            fetchDatasourceList();
            setActiveDs(data);
          }}
          onClose={() => {
            setDrawerVisible(false);
          }}
        />
        <EditDSConfig
          visible={editVisible}
          datasource={activeDs}
          onConfirm={handleEdit}
          onCancel={() => setEditVisible(false)}
        />
      </Card>
      <Modal
        open={deleteVisible}
        title={`${t("delete")} '${activeDs?.name}?'`}
        onCancel={() => setDeleteVisible(false)}
        onOk={handleDelete}
      >
        {t("delete_dialog_text", { name: activeDs?.name })}
      </Modal>
      <Modal
        width={600}
        open={exportVisible}
        onOk={() => setExportVisible(false)}
        onCancel={() => setExportVisible(false)}
        title={`Export ${activeDs.name} models`}
      >
        <Form form={scriptForm}>
          <Form.Item name="script">
            <Input.TextArea rows={10} />
          </Form.Item>
        </Form>
      </Modal>
      <Modal
        width={600}
        open={importVisible}
        onOk={importModels}
        onCancel={() => setImportVisible(false)}
        title={`Import ${activeDs.name} models`}
      >
        <Form form={scriptForm}>
          <Form.Item name="script" required>
            <Input.TextArea rows={10} />
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
};

export default DatasourceManagement;

// src/views/datasource/index.vue
<template>
  <el-row>
    <el-col :span="4">
      <el-card shadow="never">
        <div style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">DS management</div>
        <el-divider/>
        <div class="datasource-wrap">
          <div
            class="ds-item"
            :class="{ 'ds-item-active': item.name === activeDs.name }"
            v-for="(item, index) in dsList"
            :key="index"
            @click="handleItemChange(item)"
          >
            <el-icon class="p-2" size="15">
              <component :is="DbsMap[item.config?.dbKind]"/>
            </el-icon>
            {{ item.name }}
            <div class="absolute right-12px">
              <el-dropdown trigger="hover">
                <el-icon class="icon-hover invisible" @click.stop>
                  <More/>
                </el-icon>
                <template #dropdown>
                  <el-dropdown-menu>
                    <el-dropdown-item :disabled="item.type==='system'" @click.stop="deleteVisible=true; activeDs=item;">
                      <span class="text-#f56c6c">Delete</span>
                    </el-dropdown-item>
                  </el-dropdown-menu>
                </template>
              </el-dropdown>
            </div>
          </div>
        </div>
        <el-divider/>
        <div>
          <el-button type="primary" :icon="Connection" @click="drawerVisible = true" style="width: 100%" plain>
            Connect Database
          </el-button>
        </div>
      </el-card>
    </el-col>
    <el-col :span="20">
      <el-row>
        <el-col>
          <el-card shadow="never">
            <el-row>
              <el-col :span="12">{{ activeDs.name }}</el-col>
              <el-col :span="12" style="text-align: right">
                <el-button @click="router.push(`/modeling?datasource=${activeDs.name}`)">Modeling</el-button>
                <el-button @click="refreshDatasource" :loading="refreshLoading">Refresh</el-button>
                <el-button @click="tesConnection" :loading="testLoading">Test</el-button>
                <el-button type="primary" :disabled="activeDs.type==='system'" @click="editVisible = true">Edit
                </el-button>
              </el-col>
            </el-row>
          </el-card>
        </el-col>
        <el-col>
          <el-card shadow="never">
            <DatabaseInfo :datasource="activeDs"/>
          </el-card>
        </el-col>
      </el-row>
    </el-col>
  </el-row>
  <ConnectDatabase :visible="drawerVisible" @change="onChangeDatasource" @close="drawerVisible = false"/>
  <EditDSConfig :visible="editVisible" @conform="editDatabase" @cancel="editVisible = false"
                @close="editVisible = false"
                :datasource="activeDs"
                v-model="activeDs.config"/>
  <el-dialog
    v-model="deleteVisible"
    :title="`Delete '${activeDs?.name}?'`"
    width="500"
  >
    <span>Are you sure you want to delete <span class="font-bold">{{ activeDs?.name }}</span>?</span>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="deleteVisible = false">Cancel</el-button>
        <el-button type="danger" @click="handleDelete">
          Delete
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>
<script setup lang="ts">
import {ElMessage} from "element-plus";
import {
  deleteDatasource,
  getDatasourceList,
  refreshDatasource as reqRefreshDatasource,
  updateDatasource,
  validateDatasource
} from "~/api/datasource";
import {onMounted, ref} from "vue";
import {useRouter} from "vue-router";
import {Connection, More} from "@element-plus/icons-vue";
import ConnectDatabase from "~/views/datasource/ConnectDatabase.vue";
import {Datasource, DbsMap} from "~/types";
import DatabaseInfo from "~/views/datasource/DatabaseInfo.vue";
import EditDSConfig from "~/views/datasource/EditDSConfig.vue";

const router = useRouter();

const drawerVisible = ref<boolean>(false);
const editVisible = ref<boolean>(false);
const deleteVisible = ref<boolean>(false);
const dsList = ref<Datasource[]>([]);
const activeDs = ref<Datasource>({});
const refreshLoading = ref<boolean>(false);
const testLoading = ref<boolean>(false);

const reqDatasourceList = async () => {
  try {
    dsList.value = await getDatasourceList();
    activeDs.value = dsList.value[0]
  } catch (error) {
    ElMessage.error(error as Error);
  }
};
const refreshDatasource = async () => {
  refreshLoading.value = true;
  await reqRefreshDatasource(activeDs.value.name);
  refreshLoading.value = false;
  ElMessage.success('Refresh succeed');
}
const tesConnection = async () => {
  testLoading.value = true;
  const result = await validateDatasource(activeDs.value);
  testLoading.value = false;
  if (result.success) {
    ElMessage.success(`Succeed, ping: ${result.time}ms`);
  } else {
    ElMessage.error(`Failed, error msg: ${result.errorMsg}`);
  }
}
const onChangeDatasource = () => {
  reqDatasourceList();
  refreshDatasource();
}
const editDatabase = async () => {
  await updateDatasource(activeDs.value.name, activeDs.value);
  editVisible.value = false
}
const handleItemChange = (item: Datasource) => {
  activeDs.value = item;
  console.log(activeDs.value);
}
const handleDelete = async () => {
  await deleteDatasource(activeDs.value?.name);
  await reqDatasourceList();
  deleteVisible.value = false;
}

onMounted(() => {
  reqDatasourceList();
});
</script>
<style scoped lang="scss">
.datasource-wrap {
  position: relative;
  padding: 5px;

  .ds-item {
    font-size: var(--ep-font-size-base);
    height: 32px;
    line-height: 32px;
    cursor: pointer;
    white-space: nowrap;
    display: flex;
    align-items: center;
    padding: 0 4px;

    &:hover {
      background-color: var(--ep-fill-color-light);

      .icon-hover {
        visibility: visible;
        top: 10px;
      }
    }

    &-active {
      background-color: var(--ep-fill-color-light);
    }
  }
}


</style>
