// src/pages/DataSource/components/SQLiteConfig.tsx
import React from 'react';
import {Form, Input} from 'antd';
import {useTranslation} from "react-i18next";

interface Config {
  url?: string;
  username?: string;
  password?: string;
}

interface DatabaseConfigProps {
  config?: Config;
  onChange?: (changedConfig: Config) => void;
  readOnly?: boolean;
}

const SQLiteConfig: React.FC<DatabaseConfigProps> = ({ readOnly = false }) => {

  const {t} = useTranslation();

  return (
    <>
      <Form.Item name="dbKind" hidden/>
      <Form.Item
        name="url"
        label={t('connect_database_url')}
        rules={[{required: true}]}
      >
        <Input placeholder="jdbc:sqlite:path/to/database.db" readOnly={readOnly}/>
      </Form.Item>
      <Form.Item name="username" label={t('username')}>
        <Input readOnly={readOnly}/>
      </Form.Item>
      <Form.Item name="password" label={t('password')}>
        <Input.Password readOnly={readOnly}/>
      </Form.Item>
    </>
  );
};

export default SQLiteConfig;

// src/views/datasource/SQLiteConfig.vue
<template>
  <el-form label-position="top"
           :model="config">
    <el-form-item required label="Database URL" prop="url">
      <el-input placeholder="sqlite" type="file" v-model="config.file"/>
    </el-form-item>
  </el-form>
</template>
<script setup lang="ts">

const config = defineModel<any>({required: true});

</script>
<style scoped>

</style>
