// src/views/datasource/MySQLConfig.vue
<template>
  <el-form label-position="top"
           :modelValue="config">
    <el-form-item label="Database URL" prop="url">
      <el-input placeholder="jdbc:mysql://localhost:3306/db_name" v-model="config.url"/>
    </el-form-item>
    <el-form-item required label="Username" prop="username">
      <el-input v-model="config.username"/>
    </el-form-item>
    <el-form-item label="Password" prop="password">
      <el-input v-model="config.password"/>
    </el-form-item>
  </el-form>
</template>
<script setup lang="ts">
import {reactive, watchEffect} from "vue";

const props = defineProps(['modelValue']);
const emits = defineEmits(['update:modelValue']);
const config = reactive<any>({
  dbKind: 'mysql',
  url: '',
  username: '',
  password: '',
});
watchEffect(() => {
  if (props.modelValue) {
    config.dbKind = props.modelValue.dbKind;
  }
})
watchEffect(() => {
  if (config) {
    emits('update:modelValue', config);
  }
});
</script>
<style scoped>

</style>

// src/pages/DataSource/components/MySQLConfig.tsx
import React from 'react';
import {Form, Input} from 'antd';
import {useTranslation} from "react-i18next";

interface Config {
  url?: string;
  username?: string;
  password?: string;
}

interface DatabaseConfigProps {
  config?: Config;
  onChange?: (changedConfig: Config) => void;
}

const MySQLConfig: React.FC<DatabaseConfigProps> = () => {

  const {t} = useTranslation();

  return (
    <>
      <Form.Item name="dbKind" hidden/>
      <Form.Item
        name="url"
        label={t('connect_database_url')}
        rules={[{required: true}]}
      >
        <Input placeholder="jdbc:mysql://localhost:3306/db_name"/>
      </Form.Item>
      <Form.Item name="username" label={t('username')}>
        <Input/>
      </Form.Item>
      <Form.Item name="password" label={t('password')}>
        <Input.Password/>
      </Form.Item>
    </>
  );
};

export default MySQLConfig;
