// src/views/modeling/CreateModel.vue
<template>
  <el-drawer v-model="drawer" title="Create model" size="50%">
    <el-form label-position="top" :model="form">
      <el-form-item label="Name" required>
        <el-input v-model="form.name"/>
      </el-form-item>
      <el-form-item label="Comment">
        <el-input v-model="form.comment"/>
      </el-form-item>
      <el-form-item label="Fields">
        <el-table :data="form.fields" style="width: 100%">
          <el-table-column label="name" prop="name"/>
          <el-table-column label="type" prop="type">
            <template #default="{row}">
              {{ displayFieldType(row) }}
            </template>
          </el-table-column>
          <el-table-column label="unique" prop="unique"/>
          <el-table-column label="nullable" prop="nullable"/>
          <el-table-column label="comment" prop="comment"/>
          <el-table-column label="operations" width="150" fixed="right">
            <template #default="scope">
              <el-button type="primary" link @click="handleEditField(scope.$index)">
                Edit
              </el-button>
              <el-popconfirm title="Are you sure to delete this?" @confirm="delField(scope.$index)">
                <template #reference>
                  <el-button type="primary" link>
                    Delete
                  </el-button>
                </template>
              </el-popconfirm>
            </template>
          </el-table-column>
        </el-table>
        <el-button class="mt-4" style="width: 100%" @click="handleAddField">
          Add field
        </el-button>
      </el-form-item>
      <el-form-item label="Indexes">
        <el-table :data="form?.indexes" style="width: 100%">
          <el-table-column label="name" prop="name" width="200"/>
          <el-table-column label="fields" width="auto">
            <template #default="{ row }">
              <div class="flex gap-1">
                <el-tag type="info" v-for="item in row.fields">
                  {{ item?.fieldName }} {{ item.direction }}
                </el-tag>
              </div>
            </template>
          </el-table-column>
          <el-table-column label="unique" prop="unique" width="100"/>
          <el-table-column label="operations" width="150" fixed="right">
            <template #default="scope">
              <el-button type="primary" link @click="handleEditIndex(scope.$index)">
                Edit
              </el-button>
              <el-popconfirm title="Are you sure to delete this?" @confirm="delIndex(scope.$index)">
                <template #reference>
                  <el-button type="primary" link>
                    Delete
                  </el-button>
                </template>
              </el-popconfirm>
            </template>
          </el-table-column>
        </el-table>
        <el-button class="mt-4" style="width: 100%" @click="handleAddIndex">
          Add index
        </el-button>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="cancelForm">Cancel</el-button>
      <el-button type="primary" @click="submitForm">Create</el-button>
    </template>
  </el-drawer>
  <ChangeField v-model="changeFieldDialogVisible"
               :visible="changeFieldDialogVisible"
               :datasource="datasourceName"
               :model="form"
               :current-value="fieldForm"
               @conform="addOrEditField"
               @cancel="handleCancelFieldForm"
  />
  <ChangeIndex v-model="changeIndexDialogVisible"
               :datasource="datasourceName"
               :model="form"
               :current-value="indexForm"
               @conform="addOrEditIndex"
               @cancel="changeIndexDialogVisible = false"

  />
</template>
<script setup lang="ts">
import {computed, ref} from "vue";
import ChangeField from "~/views/modeling/ChangeField.vue";
import ChangeIndex from "~/views/modeling/ChangeIndex.vue";
import {displayFieldType} from "~/utils/models";
import {FieldInitialValues, Model} from "~/types";

const props = defineProps(['datasource']);
const emits = defineEmits(['conform', 'cancel']);
const drawer = defineModel<boolean>({required: true});

const changeFieldDialogVisible = ref<boolean>(false);
const changeIndexDialogVisible = ref<boolean>(false);
const form = ref<Model>({
  name: '',
  comment: '',
  fields: [
    {
      name: 'id',
      type: 'id',
      unique: true,
      nullable: false,
      generatedValue: 'AUTO_INCREMENT',
      comment: 'ID'
    }
  ],
  indexes: []
});
const fieldForm = ref<any>(FieldInitialValues['string']);
const selectedFieldKey = ref<number>(-1);
const indexForm = ref<any>({required: true});
const selectedIndexKey = ref<number>(-1);

const datasourceName = computed(() => props.datasource);


const handleAddField = () => {
  fieldForm.value = FieldInitialValues['string'];
  selectedFieldKey.value = -1;
  changeFieldDialogVisible.value = true;
}
const handleEditField = (index: number) => {
  fieldForm.value = form.value.fields[index];
  selectedFieldKey.value = index;
  changeFieldDialogVisible.value = true;
}
const handleCancelFieldForm = () => {
  fieldForm.value = {type: 'string'};
  changeFieldDialogVisible.value = false
}
const addOrEditField = (val: any) => {
  if (selectedFieldKey.value === -1) {
    form.value.fields.push(val);
  } else {
    form.value.fields[selectedFieldKey.value] = val;
  }
  changeFieldDialogVisible.value = false;
}
const delField = (index: number) => {
  form.value.fields.splice(index, 1);
}
const handleAddIndex = () => {
  indexForm.value = {};
  selectedIndexKey.value = -1;
  changeIndexDialogVisible.value = true;
}
const handleEditIndex = (index: number) => {
  indexForm.value = form.value.indexes[index];
  selectedIndexKey.value = index;
  changeIndexDialogVisible.value = true;
}
const addOrEditIndex = (val: any) => {
  if (selectedIndexKey.value === -1) {
    form.value.indexes.push(val);
  } else {
    form.value.indexes[selectedIndexKey.value] = val;
  }
  changeIndexDialogVisible.value = false;
}
const delIndex = (index: number) => {
  form.value.indexes.splice(index, 1);
}
const cancelForm = () => {
  emits('cancel');
}
const submitForm = async () => {
  emits('conform', form.value);
}

</script>
<style scoped>

</style>

// src/pages/DataModeling/components/CreateModel.tsx
import React, {useEffect, useState} from 'react';
import {Button, Drawer, Form, Input, Popconfirm, Table, Tag} from 'antd';
import {ColumnsType} from 'antd/es/table';
import {FieldInitialValues, Model} from './types';
import FieldForm from "./FieldForm.tsx";
import IndexForm from "./IndexForm.tsx";

interface Props {
  datasource: string;
  onConform: (model: Model) => void;
  onCancel: () => void;
  visible: boolean;
}

const CreateModel: React.FC<Props> = ({visible, datasource, onConform, onCancel}) => {
  const [drawerVisible, setDrawerVisible] = useState<boolean>(false);
  const [changeFieldDialogVisible, setChangeFieldDialogVisible] = useState<boolean>(false);
  const [changeIndexDialogVisible, setChangeIndexDialogVisible] = useState<boolean>(false);
  const [form] = Form.useForm();
  const [selectedFieldIndex, setSelectedFieldIndex] = useState<number>(-1);
  const [selectedIndexIndex, setSelectedIndexIndex] = useState<number>(-1);
  const [fieldForm, setFieldForm] = useState<any>(FieldInitialValues['string']);
  const [indexForm, setIndexForm] = useState<any>({});

  useEffect(() => {
    setDrawerVisible(visible);
  }, [visible]);

  const [model, setModel] = useState<Model>({
    name: '',
    comment: '',
    fields: [
      {
        name: 'id',
        type: 'id',
        unique: true,
        nullable: false,
        generatedValue: 'AUTO_INCREMENT',
        comment: 'ID',
      }
    ],
    indexes: []
  });

  const handleAddField = () => {
    setFieldForm(FieldInitialValues['string']);
    setSelectedFieldIndex(-1);
    setChangeFieldDialogVisible(true);
  };

  const handleEditField = (index: number) => {
    setFieldForm(model.fields[index]);
    setSelectedFieldIndex(index);
    setChangeFieldDialogVisible(true);
  };

  const handleCancelFieldForm = () => {
    setFieldForm(FieldInitialValues['string']);
    setChangeFieldDialogVisible(false);
  };

  const addOrEditField = (val: any) => {
    const newFields = [...model.fields];
    if (selectedFieldIndex === -1) {
      newFields.push(val);
    } else {
      newFields[selectedFieldIndex] = val;
    }
    setModel({...model, fields: newFields});
    setChangeFieldDialogVisible(false);
  };

  const handleDeleteField = (index: number) => {
    const newFields = model.fields.filter((_, i) => i !== index);
    setModel({...model, fields: newFields});
  };

  const handleAddIndex = () => {
    setIndexForm({});
    setSelectedIndexIndex(-1);
    setChangeIndexDialogVisible(true);
  };

  const handleEditIndex = (index: number) => {
    setIndexForm(model.indexes[index]);
    setSelectedIndexIndex(index);
    setChangeIndexDialogVisible(true);
  };

  const addOrEditIndex = (val: any) => {
    const newIndexes = [...model.indexes];
    if (selectedIndexIndex === -1) {
      newIndexes.push(val);
    } else {
      newIndexes[selectedIndexIndex] = val;
    }
    setModel({...model, indexes: newIndexes});
    setChangeIndexDialogVisible(false);
  };

  const handleDeleteIndex = (index: number) => {
    const newIndexes = model.indexes.filter((_, i) => i !== index);
    setModel({...model, indexes: newIndexes});
  };

  const handleSubmit = () => {
    onConform(model);
    setDrawerVisible(false);
  };

  const handleCancel = () => {
    onCancel();
    setDrawerVisible(false);
  };

  const fieldColumns: ColumnsType<any> = [
    {title: 'Name', dataIndex: 'name', key: 'name'},
    {title: 'Type', dataIndex: 'type', key: 'type', render: (text) => text},
    {title: 'Unique', dataIndex: 'unique', key: 'unique', render: (unique: boolean) => (unique ? 'Yes' : 'No')},
    {title: 'Nullable', dataIndex: 'nullable', key: 'nullable', render: (nullable: boolean) => (nullable ? 'Yes' : 'No')},
    {title: 'Comment', dataIndex: 'comment', key: 'comment'},
    {
      title: 'Operations',
      key: 'operations',
      render: (_, __, index) => (
        <>
          <Button type="link" onClick={() => handleEditField(index)}>Edit</Button>
          <Popconfirm title="Are you sure to delete this?" onConfirm={() => handleDeleteField(index)}>
            <Button type="link" danger style={{marginLeft: 8}}>Delete</Button>
          </Popconfirm>
        </>
      )
    }
  ];

  const indexColumns: ColumnsType<any> = [
    {title: 'Name', dataIndex: 'name', key: 'name'},
    {
      title: 'Fields',
      key: 'fields',
      render: (text) => (
        <div className="flex gap-1">
          {text.map((item: any) => (
            <Tag color="blue" key={item.fieldName}>
              {item.fieldName} {item.direction}
            </Tag>
          ))}
        </div>
      )
    },
    {title: 'Unique', dataIndex: 'unique', key: 'unique'},
    {
      title: 'Operations',
      key: 'operations',
      render: (_, __, index) => (
        <>
          <Button type="primary" onClick={() => handleEditIndex(index)}>Edit</Button>
          <Popconfirm title="Are you sure to delete this?" onConfirm={() => handleDeleteIndex(index)}>
            <Button type="primary" danger style={{marginLeft: 8}}>Delete</Button>
          </Popconfirm>
        </>
      )
    }
  ];

  return (
    <>
      <Drawer
        title="Create Model"
        placement="right"
        onClose={() => {
          setDrawerVisible(false);
          onCancel();
        }}
        open={drawerVisible}
        width="50%"
        footer={
          <div style={{textAlign: 'right'}}>
            <Button onClick={() => {
              setDrawerVisible(false);
              onCancel();
            }} style={{marginRight: 8}}>
              Cancel
            </Button>
            <Button onClick={() => onConform(form.getFieldsValue())} type="primary">
              Conform
            </Button>
          </div>
        }
      >
        <Form form={form} layout="vertical">
          <Form.Item label="Name" name="name" rules={[{required: true, message: 'Please input the name!'}]}>
            <Input/>
          </Form.Item>
          <Form.Item label="Comment" name="comment">
            <Input/>
          </Form.Item>
          <Form.Item label="Fields">
            <Table
              size="small"
              columns={fieldColumns}
              dataSource={model.fields}
              pagination={false}
              rowKey={(record) => record.name}
              footer={() => (
                <Button type="primary" style={{width: '100%'}} onClick={handleAddField} ghost>Add Field</Button>
              )}
            />
          </Form.Item>
          <Form.Item label="Indexes">
            <Table
              size="small"
              columns={indexColumns}
              dataSource={model.indexes}
              pagination={false}
              rowKey={(record) => record.name}
              footer={() => (
                <Button type="primary" style={{width: '100%'}} onClick={handleAddIndex} ghost>Add Index</Button>
              )}
            />
          </Form.Item>
        </Form>
      </Drawer>
      <FieldForm
        visible={changeFieldDialogVisible}
        datasource={datasource}
        model={model}
        currentValue={fieldForm}
        onConfirm={addOrEditField}
        onCancel={() => setChangeFieldDialogVisible(false)}
      />
      <IndexForm
        visible={changeIndexDialogVisible}
        datasource={datasource}
        model={model}
        currentValue={indexForm}
        onConfirm={addOrEditIndex}
        onCancel={() => setChangeIndexDialogVisible(false)}
      />
    </>
  );
};

export default CreateModel;
