// src/views/modeling/IndexList.vue
<template>
  <el-row>
    <el-col>
      <el-card shadow="never">
        <el-row>
          <el-col :span="12">{{ model?.name }}
            {{ model?.comment }}
          </el-col>
          <el-col :span="12" style="text-align: right">
            <el-button type="primary" @click="handleAdd">New index</el-button>
          </el-col>
        </el-row>
      </el-card>
    </el-col>
    <el-col>
      <el-card shadow="never">
        <el-table :data="indexList" style="width: 100%">
          <el-table-column label="name" prop="name" width="200"/>
          <el-table-column label="fields" width="auto">
            <template #default="{ row }">
              <div class="flex gap-1">
                <el-tag type="info" v-for="item in row.fields">
                  {{ item?.fieldName }} {{ item.direction }}
                </el-tag>
              </div>
            </template>
          </el-table-column>
          <el-table-column label="unique" prop="unique" width="100"/>
          <el-table-column label="operations" width="150" fixed="right">
            <template #default="scope">
              <el-button type="primary" link @click="handleEdit(scope.$index)">
                Edit
              </el-button>
              <el-popconfirm title="Are you sure to delete this?" @confirm="delIndex(scope.$index)">
                <template #reference>
                  <el-button type="primary" link>
                    Delete
                  </el-button>
                </template>
              </el-popconfirm>
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </el-col>
  </el-row>
  <ChangeIndex v-model="changeDialogVisible"
               :datasource="datasource"
               :current-value="selectedIndexForm"
               :model="model"
               @conform="addOrEditIndex"
               @cancel="changeDialogVisible = false"

  />
</template>
<script setup lang="ts">
import {ref} from "vue";
import ChangeIndex from "~/views/modeling/ChangeIndex.vue";
import {createIndex, dropIndex, modifyIndex} from "~/api/model";

const props = defineProps(['datasource', 'model']);

const indexList = defineModel<any[]>({required: true});
const changeDialogVisible = ref<boolean>(false);
const selectedIndexKey = ref<number>(-1);
const selectedIndexForm = ref<any>();

const handleAdd = () => {
  changeDialogVisible.value = true;
  selectedIndexKey.value = -1;
  selectedIndexForm.value = {};
}
const handleEdit = (index: number) => {
  selectedIndexKey.value = index;
  selectedIndexForm.value = indexList.value[index];
  changeDialogVisible.value = true;
}
const addOrEditIndex = async (item: any) => {
  if (selectedIndexKey.value == -1) {
    await createIndex(props.datasource, props.model?.name, item);
    indexList.value.push(item);
  } else {
    await modifyIndex(props.datasource, props.model?.name, item.name, item);
    indexList.value[selectedIndexKey.value] = item;
  }
  changeDialogVisible.value = false;
}
const delIndex = async (key: number) => {
  const index: any = indexList.value[key];
  await dropIndex(props.datasource, props.model?.name, index.name);
  indexList.value.splice(index, 1);
  changeDialogVisible.value = false;

}
</script>
<style scoped>

</style>

// src/pages/DataModeling/components/IndexList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Button, notification, Popconfirm, Table, Tag} from 'antd';
import {DeleteOutlined, EditOutlined, PlusOutlined} from '@ant-design/icons';
import {createIndex, dropIndex, modifyIndex} from '../../../api/model';
import IndexForm from "./IndexForm";
import type {Index} from "../data.d.ts";

interface Model {
  name?: string;
  comment?: string;
  indexes: Index[];
}

interface IndexListProps {
  datasource: string;
  model: Model;
}

const IndexList: React.FC<IndexListProps> = ({datasource, model}) => {
  const [indexList, setIndexList] = useState<Index[]>([]);
  const [changeDialogVisible, setChangeDialogVisible] = useState<boolean>(false);
  const [selectedIndexKey, setSelectedIndexKey] = useState<number>(-1);
  const [currentVal, setCurrentVal] = useState<Index>({fields: [], name: "", unique: false});

  const fetchIndexes = useCallback(async () => {
    // Replace this with actual fetch call
    // const res = await getIndexes(datasource, model?.name);
    setIndexList(model.indexes);
  }, [datasource, model?.name]);

  useEffect(() => {
    fetchIndexes();
  }, [fetchIndexes]);

  const handleAdd = () => {
    setChangeDialogVisible(true);
    setSelectedIndexKey(-1);
  };

  const handleEdit = (index: number) => {
    setSelectedIndexKey(index);
    setCurrentVal(indexList[index]);
    setChangeDialogVisible(true);
  };

  const addOrEditIndex = async (values: Index) => {
    try {
      if (selectedIndexKey === -1) {
        await createIndex(datasource, model?.name as string, values);
        setIndexList([...indexList, values]);
      } else {
        await modifyIndex(datasource, model?.name as string, values.name, values);
        const updatedIndexes = [...indexList];
        updatedIndexes[selectedIndexKey] = values;
        setIndexList(updatedIndexes);
      }
      setChangeDialogVisible(false);
      notification.success({message: 'Index saved successfully'});
    } catch (error) {
      console.error(error);
      notification.error({message: 'Failed to save index'});
    }
  };

  const delIndex = async (key: number) => {
    try {
      const index = indexList[key];
      await dropIndex(datasource, model?.name as string, index.name);
      setIndexList(indexList.filter((_, i) => i !== key));
      notification.success({message: 'Index deleted successfully'});
    } catch (error) {
      console.error(error);
      notification.error({message: 'Failed to delete index'});
    }
  };

  const columns = [
    {title: 'Name', dataIndex: 'name', key: 'name'},
    {
      title: 'Fields',
      dataIndex: 'fields',
      key: 'fields',
      render: (fields: { fieldName: string; direction: string }[]) => (
        <div>
          {fields.map((field, index) => (
            <Tag key={index} color="default">
              {field.fieldName} {field.direction}
            </Tag>
          ))}
        </div>
      ),
    },
    {title: 'Unique', dataIndex: 'unique', key: 'unique', render: (unique: boolean) => (unique ? 'Yes' : 'No')},
    {
      title: 'Operations',
      key: 'operations',
      render: (_: any, _record: Index, index: number) => (
        <div>
          <Button
            type="link"
            icon={<EditOutlined/>}
            onClick={() => handleEdit(index)}
          >
            Edit
          </Button>
          <Popconfirm
            title="Are you sure to delete this index?"
            onConfirm={() => delIndex(index)}
          >
            <Button
              type="link"
              danger
              icon={<DeleteOutlined/>}
            >
              Delete
            </Button>
          </Popconfirm>
        </div>
      ),
    },
  ];

  return (
    <div style={{padding: '20px'}}>
      <div>
        <div style={{display: 'flex', justifyContent: 'space-between'}}>
          <div>
            {model?.name} {model?.comment}
          </div>
          <Button
            type="primary"
            icon={<PlusOutlined/>}
            onClick={handleAdd}
          >
            New Index
          </Button>
        </div>
      </div>
      <div style={{marginTop: 16}}>
        <Table
          size="small"
          rowKey="name"
          dataSource={indexList}
          columns={columns}
          pagination={false}
        />
      </div>
      <IndexForm
        visible={changeDialogVisible}
        datasource={datasource}
        model={model}
        currentValue={currentVal}
        onConfirm={addOrEditIndex}
        onCancel={() => setChangeDialogVisible(false)}/>
    </div>
  );
};

export default IndexList;
