// src/pages/IdentityProvider/components/CreateProvider.tsx
import React, {useState} from 'react';
import {Button, Col, Drawer, Form, Input, message, Radio, Row, Steps} from 'antd';
import {createIdentityProvider} from "../../../api/identity-provider.ts";
import IdPInfo from "./IdPInfo.tsx";
import {css} from "@emotion/css";

interface CreateProviderProps {
  visible: boolean;
  onClose: () => void;
  onConfirm: (provider: any) => void;
}

const CreateProvider: React.FC<CreateProviderProps> = ({visible, onClose, onConfirm}) => {
  const [form] = Form.useForm();
  const [currentStep, setCurrentStep] = useState(0);
  const [formData, setFormData] = useState<any>({
    name: '',
    type: 'oidc',
    issuer: '',
    clientId: '',
    clientSecret: ''
  });

  const next = () => setCurrentStep((prev) => Math.min(prev + 1, 2));
  const prev = () => setCurrentStep((prev) => Math.max(prev - 1, 0));

  const handleCreateProvider = async () => {
    try {
      const values = await form.validateFields();
      const newProvider = {name: values.name, provider: values};
      const res = await createIdentityProvider(newProvider);
      setFormData(res);
      message.success('Provider created successfully');
      next();
      onConfirm(res);
    } catch (error) {
      console.log(error)
      message.error('Failed to create provider');
    }
  };

  const segmentTitle = css`
    font-size: 16px;
    font-weight: bold;
    padding-bottom: 10px;
  `;

  return (
    <Drawer
      title="New provider"
      width="50%"
      visible={visible}
      onClose={onClose}
      footer={
        <>
          {currentStep !== 0 && currentStep !== 2 && (
            <Button onClick={prev} style={{marginRight: 8}}>
              Go back
            </Button>
          )}
          {currentStep === 0 && (
            <Button type="primary" onClick={next}>
              Select provider
            </Button>
          )}
          {currentStep === 1 && (
            <Button type="primary" onClick={handleCreateProvider}>
              Create provider
            </Button>
          )}
        </>
      }
    >
      <Steps current={currentStep} size="small">
        <Steps.Step title="Select provider"/>
        <Steps.Step title="Create provider"/>
        <Steps.Step title="Success"/>
      </Steps>

      <Form
        form={form}
        layout="vertical"
        initialValues={formData}
        onValuesChange={(changedValues) => setFormData((prev: any) => ({...prev, ...changedValues}))}
        style={{marginTop: 24}}
      >
        <Form.Item hidden name="type" initialValue="oidc">
          <Input/>
        </Form.Item>
        {currentStep === 0 && (
          <Form.Item name="type" initialValue="oidc" label="Please select your IdP to create">
            <Radio.Group name="type">
              <div className={segmentTitle}>User-defined</div>
              <Radio value="oidc">OpenID Connect (oidc)</Radio>
              <div className={segmentTitle}>Social</div>
              <Radio value="github" disabled>
                Github (github)
              </Radio>
            </Radio.Group>
          </Form.Item>
        )}

        {currentStep === 1 && (
          <>
            <Form.Item
              name="name"
              label="Display name"
              rules={[{required: true, message: 'Please enter the display name'}]}
            >
              <Input/>
            </Form.Item>

            <Form.Item
              label="Issuer"
              name="issuer"
              rules={[{required: true, message: 'Issuer is required'}]}
            >
              <Input placeholder="e.g. http://localhost:8080/realms/master"/>
            </Form.Item>

            {/* Discovery endpoint */}
            {formData.issuer && <Form.Item label="Discovery endpoint">
              {formData.issuer}/.well-known/openid-configuration
            </Form.Item>}


            {/* Client ID */}
            <Form.Item
              label="Client ID"
              name="clientId"
              rules={[{required: true, message: 'Client ID is required'}]}
            >
              <Input/>
            </Form.Item>

            {/* Client Secret */}
            <Form.Item
              label="Client Secret"
              name="clientSecret"
              rules={[{required: true, message: 'Client Secret is required'}]}
            >
              <Input/>
            </Form.Item>
          </>
        )}

        {currentStep === 2 && (
          <Row justify="center">
            <Col span={24} style={{textAlign: 'center'}}>
              <p>Created successfully</p>
              <IdPInfo data={formData}/>
              <Button type="primary" style={{marginTop: 12}} onClick={() => {
                onClose();
                setCurrentStep(0);
              }}>
                Close
              </Button>
            </Col>
          </Row>
        )}
      </Form>
    </Drawer>
  );
};

export default CreateProvider;

// src/views/idps/CreateProvider.vue
<template>
  <el-drawer @close="active=0" v-model="visible" title="New provider" size="50%">
    <div style="padding-bottom: 20px">
      <el-steps :active="active" finish-status="success" align-center>
        <el-step title="Select provider"/>
        <el-step title="Create provider"/>
      </el-steps>
    </div>
    <el-form
      label-position="top"
      label-width="auto"
      :model="form"
    >
      <div v-if="active==0">
        <el-form-item class="mb-2 flex items-center text-sm"
                      label="Please select your IdP to create.">
          <div class="mb-2 flex items-center text-sm">
            <el-radio-group class="ml-4" v-model="form.provider.type">
              <div class="segment-title">User-defined</div>
              <el-radio value="oidc" border>OpenID Connect (oidc)</el-radio>
              <div class="segment-title">Social</div>
              <el-radio value="github" border disabled>Github (github)</el-radio>
            </el-radio-group>
          </div>
        </el-form-item>
      </div>
      <div v-if="active==1">
        <el-form-item required label="Display name">
          <el-input v-model="form.name"/>
        </el-form-item>
      </div>
    </el-form>
    <div v-if="active==1">
      <OIdcProvider v-if="form.provider.type === 'oidc'" v-model="form.provider"/>
    </div>
    <div v-if="active==2">
      <el-row>
        <el-col class="pb5">
          <span class="text-center">Created successfully</span>
        </el-col>
        <el-col>
          <IdPInfo v-model="form"/>
        </el-col>
        <el-col class="text-center">
          <el-button style="margin-top: 12px" @click="visible = false">Close</el-button>
        </el-col>
      </el-row>
    </div>
    <template #footer>
      <el-button style="margin-top: 12px" @click="prev" v-if="active!=0 && active!=2">Go back</el-button>
      <el-button type="primary" style="margin-top: 12px" @click="next" v-if="active==0">Select provider</el-button>
      <el-button type="primary" style="margin-top: 12px" @click="createProvider" v-if="active==1">Create provider
      </el-button>
    </template>
  </el-drawer>
</template>
<script setup lang="ts">
import {ref} from "vue";
import OIdcProvider from "~/views/idps/OIdcProvider.vue";
import {IdentifyProvider} from "~/types";
import {createIdentityProvider} from "~/api/identity-provider";
import IdPInfo from "~/views/idps/IdPInfo.vue";

const emits = defineEmits(['change']);

const visible = defineModel('visible');

const form = ref<IdentifyProvider>({name: '', provider: {type: 'oidc'}});
const active = ref(0);

const prev = () => {
  if (active.value-- < 0) active.value = 0
}
const next = () => {
  if (active.value++ > 2) active.value = 0
}
const createProvider = async () => {
  const res = await createIdentityProvider(form.value);
  next();
  emits('change', res);
}

</script>
<style scoped>
.ep-radio {
  margin: 5px;
}

.ep-radio-group {
  display: flex;
  align-items: center;
}

.segment-title {
  font-size: 14px;
  width: 100%;
  font-weight: 600;
  padding-bottom: 10px;
  padding-top: 10px;
}
</style>
