// src/pages/IdPManagement/components/EditProvider.tsx
import React from 'react';
import { Modal, Form, Input, Button } from 'antd';
import OIdcProvider from "./OIdcProvider.tsx";

interface EditProviderProps {
  visible: boolean;
  form: any;
  onCancel: () => void;
  onConfirm: (form: any) => void;
}

const EditProvider: React.FC<EditProviderProps> = ({ visible, form, onCancel, onConfirm }) => {
  const [currentForm, setCurrentForm] = React.useState(form);

  const handleConfirm = () => {
    onConfirm(currentForm);
  };

  return (
    <Modal
      title="Edit provider"
      visible={visible}
      onCancel={onCancel}
      footer={[
        <Button key="cancel" onClick={onCancel}>
          Cancel
        </Button>,
        <Button key="submit" type="primary" onClick={handleConfirm}>
          Confirm
        </Button>,
      ]}
    >
      <Form layout="vertical">
        {/* Connection Name */}
        <Form.Item label="Connection name">
          <Input value={currentForm?.name} readOnly disabled />
        </Form.Item>

        {/* OIDC Provider, assuming this is a custom component */}
        <OIdcProvider provider={currentForm?.provider} setProvider={(provider) => setCurrentForm({ ...currentForm, provider })} />
      </Form>
    </Modal>
  );
};

export default EditProvider;

// src/views/idps/EditProvider.vue
<template>
  <el-dialog v-model="visible" width="500px">
    <template #header>
      Edit provider
    </template>
    <el-form :model="form" label-position="top">
      <el-form-item label="Connection name" prop="name">
        <el-input :model-value="form.name" readonly disabled/>
      </el-form-item>
      <OIdcProvider v-model="form.provider"/>
    </el-form>
    <template #footer>
      <el-button @click="cancelForm">Cancel</el-button>
      <el-button type="primary" @click="submitForm">Conform</el-button>
    </template>
  </el-dialog>
</template>
<script setup lang="ts">
import OIdcProvider from "~/views/idps/OIdcProvider.vue";

const emits = defineEmits(['conform', 'cancel']);

const form = defineModel<any>({required: true});
const visible = defineModel<boolean>('visible');

const cancelForm = () => {
  emits('cancel');
}
const submitForm = () => {
  emits('conform', form);
}
</script>
<style scoped>

</style>
