// src/components/HidePassword.vue
<template>
  <div>
    {{ isHide ? '***********' : text }}
    <el-button :icon="isHide? Hide : View" v-model="isHide" @click="isHide=!isHide" link/>
  </div>
</template>
<script setup lang="ts">
import {ref, watchEffect} from "vue";
import {Hide, View,} from "@element-plus/icons-vue";

const props = defineProps(['text']);

const isHide = ref<boolean>(true);
const text = ref<string>();

watchEffect(() => {
  text.value = props.text;
  isHide.value = true;
});
</script>
<style scoped>

</style>

// src/components/HidePassword.tsx
import React, { useState } from 'react';
import { Button, Typography } from 'antd';
import { EyeInvisibleOutlined, EyeOutlined } from '@ant-design/icons';

interface HidePasswordProps {
  text: string;
}

const HidePassword: React.FC<HidePasswordProps> = ({ text }) => {
  const [isHide, setIsHide] = useState<boolean>(true);

  const toggleHide = () => {
    setIsHide(!isHide);
  };

  return (
    <div>
      <Typography.Text>
        {isHide ? '***********' : text}
      </Typography.Text>
      <Button
        type="link"
        icon={isHide ? <EyeOutlined /> : <EyeInvisibleOutlined />}
        onClick={toggleHide}
      />
    </div>
  );
};

export default HidePassword;
