// src/components/InputVariables.vue
<template>
  <el-input v-model="input" :placeholder="placeholder" clearable>
    <template #suffix>
      <el-dropdown trigger="click">
        <el-button title="Add variables" @click.stop size="small" link>{...}</el-button>
        <template #dropdown>
          <el-dropdown-menu style="height: 300px">
            <el-dropdown-item :key="item" v-for="item in variableKeys" @click.stop="selectVariable(item)">
              {{ item }}
            </el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
    </template>
  </el-input>
</template>
<script setup lang="ts">
import {computed, ref, watchEffect} from "vue";
import {getVariables} from "~/api/environment";

const props = defineProps(['modelValue', 'placeholder']);
const emits = defineEmits(['update:modelValue']);
const input = ref<string>('');
const variables = ref<any[]>([]);
const reqVariables = async () => {
  variables.value = await getVariables()
}
reqVariables();
const variableKeys = computed(() => {
  const list = [];
  list.push(...Object.keys(variables.value['environment'] || {}));
  list.push(...Object.keys(variables.value['system'] || {}));
  return list;
});
const selectVariable = (item: string) => {
  input.value += `{{${item}}}`;
}
watchEffect(() => {
  if (input.value) {
    emits('update:modelValue', input.value);
  }
});
watchEffect(() => {
  if (props.modelValue) {
    input.value = props.modelValue;
  }
});
</script>
<style scoped>

</style>

// src/components/InputVariables.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Input, Button, Dropdown, Menu } from 'antd';
import { DownOutlined } from '@ant-design/icons';
import {getVariables} from "../api/environment.ts";

interface InputVariablesProps {
  placeholder?: string;
}

const InputVariables: React.FC<InputVariablesProps> = ({ placeholder }) => {
  const [input, setInput] = useState<string>('');
  const [variables, setVariables] = useState<Record<string, any>>({});

  const reqVariables = useCallback(async () => {
    const result = await getVariables();
    setVariables(result);
  }, []);

  useEffect(() => {
    reqVariables();
  }, [reqVariables]);

  const variableKeys = [
    ...(Object.keys(variables['environment'] || {})),
    ...(Object.keys(variables['system'] || {})),
  ];

  const handleMenuClick = (item: { key: string }) => {
    setInput(`\${${item.key}}`);
  };

  const menu = (
    <Menu onClick={handleMenuClick}>
      {variableKeys.map((key) => (
        <Menu.Item key={key}>{key}</Menu.Item>
      ))}
    </Menu>
  );

  return (
    <Input
      value={input}
      placeholder={placeholder}
      suffix={
        <Dropdown overlay={menu} trigger={['click']}>
          <Button size="small" type="link" icon={<DownOutlined />} />
        </Dropdown>
      }
      onChange={(e) => setInput(e.target.value)}
    />
  );
};

export default InputVariables;
