// src/pages/ApiManagement/components/RequestMethodTag.tsx
import React from 'react';

interface RequestMethodTagProps {
  method: string;
}

const RequestMethodTag: React.FC<RequestMethodTagProps> = ({ method }) => {
  const getMethodStyle = (method: string): React.CSSProperties => {
    switch (method) {
      case 'GET':
        return { color: 'green' };
      case 'POST':
        return { color: 'goldenrod' };
      case 'PUT':
        return { color: 'mediumblue' };
      case 'DELETE':
        return { color: 'red' };
      default:
        return {};
    }
  };

  const getMethodLabel = (method: string): string => {
    switch (method) {
      case 'DELETE':
        return 'DEL';
      case 'PUT':
        return 'PUT';
      case 'GET':
        return 'GET';
      case 'POST':
        return 'POST';
      default:
        return method;
    }
  };

  return (
    <div className="tree-item-icon" style={{ textAlign: 'right', fontWeight: 'bold' }}>
      <span style={getMethodStyle(method)}>
        {method === 'GET' || method === 'PUT' || method === 'DELETE' ? `\u00A0\u00A0${getMethodLabel(method)}` : getMethodLabel(method)}
      </span>
    </div>
  );
};

export default RequestMethodTag;

// src/components/RequestMethodTag.vue
<template>
  <div class="tree-item-icon">
    <span v-if="method=='GET'" style="color: green;">&nbsp;&nbsp;GET</span>
    <span v-else-if="method=='POST'" style="color: goldenrod;">POST</span>
    <span v-else-if="method=='PUT'" style="color: mediumblue;">&nbsp;&nbsp;PUT</span>
    <span v-else-if="method=='DELETE'" style="color: red;">&nbsp;&nbsp;DEL</span>
    <span v-else>{{ method }}</span>
  </div>
</template>
<script setup lang="ts">
const props = defineProps(['method']);
</script>

<style scoped>
.tree-item-icon {
  text-align: right;
  font-weight: bold;
}
</style>
