// src/pages/DataModeling/components/SelectModel.tsx
import React, {useEffect, useRef, useState} from 'react';
import {Button, Divider, Dropdown, Input, Menu, Modal, Select, Space, Spin, Tree} from 'antd';
import {
  DeleteOutlined,
  EditOutlined,
  MoreOutlined,
  PlusOutlined,
  ReloadOutlined,
  TableOutlined
} from '@ant-design/icons';
import {getDatasourceList, refreshDatasource as reqRefreshDatasource} from '../../../api/datasource';
import {createModel as reqCreateModel, dropModel, getModelList} from '../../../api/model';
import {css} from "@emotion/css";
import {useNavigate} from "react-router-dom";
import CreateModel from "./CreateModel.tsx";

interface Datasource {
  name: string;
  config?: { dbKind?: string };
}

interface Model {
  name: string;
  children?: Model[];
}

interface SelectModelProps {
  datasource: string;
  editable: boolean;
  onChange: (ds: string, model: Model) => void;
}

const SelectModel: React.FC<SelectModelProps> = ({datasource, editable, onChange}) => {

  const navigate = useNavigate();
  const [activeDs, setActiveDs] = useState<string>(datasource);
  const [dsList, setDsList] = useState<Datasource[]>([]);
  const [modelList, setModelList] = useState<Model[]>([]);
  const [filteredModelList, setFilteredModelList] = useState<Model[]>([]); // 增加状态来保存过滤后的数据
  const [activeModel, setActiveModel] = useState<Model | null>(null);
  const [dsLoading, setDsLoading] = useState<boolean>(false);
  const [modelLoading, setModelLoading] = useState<boolean>(false);
  const [deleteDialogVisible, setDeleteDialogVisible] = useState<boolean>(false);
  const [createDrawerVisible, setCreateDrawerVisible] = useState(false);
  const [filterText, setFilterText] = useState<string>(''); // 监听搜索框输入
  const treeRef = useRef<any>(null);
  // 添加模型
  const addModel = async (item: any) => {
    await reqCreateModel(activeDs, item);
    setCreateDrawerVisible(false);
    await reqModelList();
  };

  // 获取数据源列表
  const reqDatasourceList = async () => {
    const res = await getDatasourceList();
    setDsList(res);
    setActiveDs(datasource || res[0].name);
  };

  // 获取模型列表
  const reqModelList = async () => {
    setModelLoading(true);
    const res: Model[] = await getModelList(activeDs);
    setModelLoading(false);
    setModelList(res);
    setFilteredModelList(res); // 初始化时未过滤
    setActiveModel(res[0] || null);
    onChange(activeDs, res[0] || null);
  };

  // 处理模型选择
  const handleItemChange = (item: Model) => {
    setActiveModel(item);
    onChange(activeDs, item);
  };

  // 刷新数据源
  const refreshDatasource = async () => {
    setDsLoading(true);
    await reqRefreshDatasource(activeDs);
    setDsLoading(false);
  };

  // 删除模型
  const handleDelete = async () => {
    if (activeModel) {
      await dropModel(activeDs, activeModel.name);
      await reqModelList();
      setDeleteDialogVisible(false);
    }
  };

  // 选择数据源
  const onSelectDatasource = (value: string) => {
    setActiveDs(value);
  };

  // 处理菜单点击
  const handleMenuClick = (e: any) => {
    if (e.key === 'delete') {
      setDeleteDialogVisible(true);
    }
  };

  // 过滤树形结构数据
  const filterModelTree = (models: Model[], searchText: string): Model[] => {
    return models
      .map(model => {
        const filteredChildren = model.children ? filterModelTree(model.children, searchText) : [];
        if (model.name.toLowerCase().includes(searchText.toLowerCase()) || filteredChildren.length > 0) {
          return {...model, children: filteredChildren};
        }
        return null;
      })
      .filter(Boolean) as Model[];
  };

  // 搜索框变化时，更新过滤的树数据
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setFilterText(value);
    if (value) {
      const filteredData = filterModelTree(modelList, value);
      setFilteredModelList(filteredData);
    } else {
      setFilteredModelList(modelList);
    }
  };

  // 获取数据源列表时执行
  useEffect(() => {
    reqDatasourceList();
  }, []);

  // 获取模型列表时执行
  useEffect(() => {
    if (activeDs) {
      reqModelList();
    }
  }, [activeDs]);

  return (
    <div>
      <Select
        value={activeDs}
        onChange={onSelectDatasource}
        placeholder="Data source"
        style={{width: 'calc(100% - 50px)'}}
      >
        {dsList.map(item => (
          <Select.Option key={item.name} value={item.name}>
            <div style={{display: 'flex', alignItems: 'center'}}>
              {item.name}
            </div>
          </Select.Option>
        ))}
        <Select.Option value="manage" disabled>
          <Button
            type="link"
            icon={<EditOutlined/>}
            style={{width: '100%'}}
            onClick={() => navigate('/datasource')}
          >
            Management
          </Button>
        </Select.Option>
      </Select>
      <Button
        icon={<ReloadOutlined/>}
        onClick={refreshDatasource}
        loading={dsLoading}
        style={{marginLeft: 8}}
      />
      <Divider/>
      <Space>
        <Dropdown overlay={
          <Menu>
            <Menu.Item onClick={() => setCreateDrawerVisible(true)}>New Entity</Menu.Item>
            <Menu.Item onClick={() => null} disabled>New Enum</Menu.Item>
          </Menu>
        }>
          <Button icon={<PlusOutlined/>}/>
        </Dropdown>
        <Input
          placeholder="Search Models"
          value={filterText}
          onChange={handleSearchChange} // 绑定搜索框变化事件
          style={{width: '100%'}}
          allowClear
        />
      </Space>
      <Divider/>
      <Spin spinning={modelLoading}>
        <Tree
          className={css`
            .ant-tree-switcher {
              display: none;
            }
          `}
          ref={treeRef}
          height={380}
          treeData={filteredModelList} // 使用过滤后的数据
          fieldNames={{key: 'name', title: 'name', children: 'children'}}
          selectedKeys={[activeModel?.name || '']}
          onSelect={(_, {node}) => handleItemChange(node)}
          titleRender={node => (
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '220px'}}>
              <div style={{display: 'flex', alignItems: 'center'}}>
                <Space>
                  <TableOutlined/>
                  <span title={node.name}
                        style={{textOverflow: 'ellipsis', overflow: 'hidden', width: '180px', display: 'block'}}>
                    {node.name}
                  </span>
                </Space>
              </div>
              {editable && (
                <Dropdown
                  overlay={
                    <Menu onClick={handleMenuClick}>
                      <Menu.Item key="delete" style={{color: 'red'}} icon={<DeleteOutlined/>}>
                        Delete
                      </Menu.Item>
                    </Menu>
                  }
                  trigger={['click']}
                >
                  <MoreOutlined style={{cursor: 'pointer'}}/>
                </Dropdown>
              )}
            </div>
          )}
        />
      </Spin>
      <Modal
        title={`Delete '${activeModel?.name}'?`}
        open={deleteDialogVisible}
        onCancel={() => setDeleteDialogVisible(false)}
        onOk={handleDelete}
      >
        <p>Are you sure you want to delete <strong>{activeModel?.name}</strong>?</p>
      </Modal>
      <CreateModel visible={createDrawerVisible} datasource={activeDs} onConform={addModel}
                   onCancel={() => setCreateDrawerVisible(false)}/>
    </div>
  );
};

export default SelectModel;

// src/components/SelectModel.vue
<template>
  <div>
    <el-select v-model="activeDs" placeholder="Data source" style="width: calc(100% - 50px);">
      <el-option
        v-for="item in dsList"
        :key="item.name"
        :value="item.name">
        <template #default>
          <el-icon class="p-1">
            <component :is="DbsMap[item.config?.dbKind]"/>
          </el-icon>
          {{ item.name }}
        </template>
      </el-option>
      <template #footer>
        <el-button @click="router.push('/datasource')" type="primary" :icon="Edit" style="width: 100%" link>
          Management
        </el-button>
      </template>
    </el-select>
    <el-button class="ml-1" :icon="Refresh" @click="refreshDatasource" :loading="dsLoading"/>
  </div>
  <el-divider/>
  <div>
    <el-input
      style="width: 100%"
      placeholder="Search models"
      v-model="filterText"
      @input="onQueryChanged"
      clearable
    >
    </el-input>
  </div>
  <el-divider/>
  <el-tree-v2
    v-loading="modelLoading"
    ref="treeRef"
    :height="300"
    node-key="name"
    :highlight-current="true"
    :current-node-key="activeModel?.name"
    :data="modelList"
    :props="treeProps"
    @node-click="handleItemChange"
    :filter-method="filterMethod">
    <template #default="{ node, data }">
      <div class="flex items-center justify-between">
        <div class="flex">
          <div>
            <el-icon>
              <Document/>
            </el-icon>
          </div>
          <div class="tree-item-content">
            <span>{{ node.label }}</span>
          </div>
        </div>
        <div v-if="editable" class="absolute right-12px">
          <el-dropdown trigger="hover">
            <el-icon class="tree-item-more invisible" @click.stop>
              <More/>
            </el-icon>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item @click.stop="deleteDialogVisible = true; activeModel = data">
                  <span class="text-#f56c6c">Delete</span>
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </div>
    </template>
  </el-tree-v2>
  <el-dialog
    v-model="deleteDialogVisible"
    :title="`Delete '${activeModel?.name}?'`"
    width="500"
  >
    <span>Are you sure you want to delete <span class="font-bold">{{ activeModel?.name }}</span>?</span>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="deleteDialogVisible = false">Cancel</el-button>
        <el-button type="danger" @click="handleDelete">
          Delete
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>
<script setup lang="ts">

import {Datasource, DbsMap} from "~/types";
import {Document, Edit, More, Refresh} from "@element-plus/icons-vue";
import {onMounted, ref, watchEffect} from "vue";
import {getDatasourceList, refreshDatasource as reqRefreshDatasource} from "~/api/datasource";
import {useRouter} from "vue-router";
import {dropModel, getModelList} from "~/api/model";
import {TreeNode} from "element-plus";


const props = defineProps(['datasource', 'height', 'editable']);
const emits = defineEmits(['change']);

const router = useRouter()

const activeDs = ref<string>(props.datasource);
const activeModel = ref<any>({});
const dsList = ref<Datasource[]>([]);
const modelList = ref<any[]>([]);
const dsLoading = ref<boolean>(false);
const modelLoading = ref(false);
const deleteDialogVisible = ref<boolean>(false);
const treeRef = ref<InstanceType<any>>()
const filterText = ref<string>();

const reqDatasourceList = async () => {
  const res = await getDatasourceList();
  dsList.value = res;
  activeDs.value = props.datasource || res[0].name;
};
const reqModelList = async () => {
  modelLoading.value = true;
  const res: any = await getModelList(activeDs.value);
  modelLoading.value = false;
  modelList.value = res;
  activeModel.value = res[0];
  emits('change', activeDs.value, res[0]);
};
const filterMethod = (query: string, node: TreeNode) => {
  return node.name!.includes(query)
}
const onQueryChanged = (query: string) => {
  treeRef.value!.filter(query);
}
const handleItemChange = (item: any) => {
  activeModel.value = item;
  emits('change', activeDs.value, item);
}
const refreshDatasource = async () => {
  dsLoading.value = true;
  modelList.value = await reqRefreshDatasource(activeDs.value);
  dsLoading.value = false;
}
const handleDelete = async () => {
  await dropModel(activeDs.value, activeModel.value.name);
  await reqModelList();
  deleteDialogVisible.value = false;
}

const treeProps = {
  value: 'name',
  children: 'children',
  label: 'name',
}

watchEffect(() => {
  if (activeDs.value) {
    reqModelList();
  }
});
defineExpose({
  reload: () => {
    reqModelList();
  }
});
onMounted(() => {
  reqDatasourceList();
});
</script>
<style scoped lang="scss">
.tree-item-content {
  padding-left: 5px;
}

.ep-tree-node {
  &:hover {
    .tree-item-more {
      visibility: visible;
    }
  }

}
</style>
